/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BorrowService } from "../borrow.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BorrowCreateInput } from "./BorrowCreateInput";
import { Borrow } from "./Borrow";
import { BorrowFindManyArgs } from "./BorrowFindManyArgs";
import { BorrowWhereUniqueInput } from "./BorrowWhereUniqueInput";
import { BorrowUpdateInput } from "./BorrowUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BorrowControllerBase {
  constructor(
    protected readonly service: BorrowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Borrow })
  @nestAccessControl.UseRoles({
    resource: "Borrow",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBorrow(@common.Body() data: BorrowCreateInput): Promise<Borrow> {
    return await this.service.createBorrow({
      data: {
        ...data,

        book: data.book
          ? {
              connect: data.book,
            }
          : undefined,

        member: data.member
          ? {
              connect: data.member,
            }
          : undefined,
      },
      select: {
        book: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDueDate: true,
        id: true,

        member: {
          select: {
            id: true,
          },
        },

        returnDate: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Borrow] })
  @ApiNestedQuery(BorrowFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Borrow",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async borrows(@common.Req() request: Request): Promise<Borrow[]> {
    const args = plainToClass(BorrowFindManyArgs, request.query);
    return this.service.borrows({
      ...args,
      select: {
        book: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDueDate: true,
        id: true,

        member: {
          select: {
            id: true,
          },
        },

        returnDate: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Borrow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Borrow",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async borrow(
    @common.Param() params: BorrowWhereUniqueInput
  ): Promise<Borrow | null> {
    const result = await this.service.borrow({
      where: params,
      select: {
        book: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endDueDate: true,
        id: true,

        member: {
          select: {
            id: true,
          },
        },

        returnDate: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Borrow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Borrow",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBorrow(
    @common.Param() params: BorrowWhereUniqueInput,
    @common.Body() data: BorrowUpdateInput
  ): Promise<Borrow | null> {
    try {
      return await this.service.updateBorrow({
        where: params,
        data: {
          ...data,

          book: data.book
            ? {
                connect: data.book,
              }
            : undefined,

          member: data.member
            ? {
                connect: data.member,
              }
            : undefined,
        },
        select: {
          book: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          endDueDate: true,
          id: true,

          member: {
            select: {
              id: true,
            },
          },

          returnDate: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Borrow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Borrow",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBorrow(
    @common.Param() params: BorrowWhereUniqueInput
  ): Promise<Borrow | null> {
    try {
      return await this.service.deleteBorrow({
        where: params,
        select: {
          book: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          endDueDate: true,
          id: true,

          member: {
            select: {
              id: true,
            },
          },

          returnDate: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
